### ISSUE TITLE
instagram-analytics stopped working

### ISSUE THREAD

**Issue by HanneMaes** [kevva/instagram-analytics#4]
I made a script that runs instagram-analytics every day
But  since 2017/11/7 it stopped working and I get this error:

`events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Instagram returned status code: 404)
    at InstagramPosts.emit (events.js:144:17)
    at Stream.<anonymous> (/volume1/homes/RanzigenDanny/CloudStation/Form-Follows-Function/projects-personal/instagram-follower-flow-backend-fix/src/node_modules/instagram-screen-scrape/lib/posts.js:69:22)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Request.<anonymous> (/volume1/homes/RanzigenDanny/CloudStation/Form-Follows-Function/projects-personal/instagram-follower-flow-backend-fix/src/node_modules/instagram-screen-scrape/lib/util.js:25:24)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestResponse (/volume1/homes/RanzigenDanny/CloudStation/Form-Follows-Function/projects-personal/instagram-follower-flow-backend-fix/src/node_modules/request/request.js:1029:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
`

**Comment by ENT8R** [comment]
I'm getting the exact same error too...

**Comment by laurensiusadi** [comment]
Same error here

**Comment by victorsc** [comment]
same here

**Comment by saveroo** [comment]
are the issue coming from one of the dependencies ?

`Error: Unhandled "error" event. (Instagram returned status code: 404)
    at InstagramPosts.emit (events.js:185:19)
`

`
const Instagram = require('instagram-screen-scrape');
`

`instagram-screen-scrape/lib/posts.js`

**Comment by victorsc** [comment]
@saveroo  exactly. 

https://github.com/slang800/instagram-screen-scrape/issues/32

**Comment by saveroo** [comment]
seems like no workaround over this, either you have to fork and fix it yourself if it's possible since the endpoint is removed.. i ended up scraping the user json and made my own.

**Comment by ThinkDigitalSoftware** [comment]
@saveroo, why don't you submit a pull request? That'll help the community.
